name: validate renovate config

on:
  push:
  pull_request:

env:
  LOG_LEVEL: debug

jobs:
  matrix-preparation:
    name: Matrix preparation
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: set matrix
        id: set-matrix
        run: |
          file_list=()
          for file in *.json presets/*.json; do
              file_list+=("\"$file\"")
          done
          # Join array elements with comma and format as JSON array
          json_files=$(IFS=,; echo "[${file_list[*]}]")
          echo "matrix={\"file\":$json_files}" >> $GITHUB_OUTPUT

  validate-renovate-config:
    name: Validate Renovate config
    runs-on: ubuntu-latest
    needs: matrix-preparation
    timeout-minutes: 5
    strategy:
      matrix: ${{fromJson(needs.matrix-preparation.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v4

      - name: validate ${{ matrix.file }}
        run: npx -p renovate renovate-config-validator ${{ matrix.file }}
