name: validate renovate config

on:
  push:
  pull_request:

env:
  LOG_LEVEL: debug

jobs:
  validate-renovate-config:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      CI: true

    steps:
      - uses: actions/checkout@v4
      - name: Validate renovate config
        run: |
          for file in *.json presets/*.json; do
            echo "[CI] validate $file"
            RENOVATE_CONFIG_FILE=${file} npx renovate renovate-config-validator
          done
